[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Mjolnir-ucph"
authors = [{name = "Bent Petersen", email = "bent.petersen@sund.ku.dk"}]
dynamic = ["version", "description"]
